[2025-03-07T06:29:02.801+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-07T06:29:02.806+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_payments.etl_process manual__2025-03-07T06:28:58.540212+00:00 [queued]>
[2025-03-07T06:29:02.809+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_payments.etl_process manual__2025-03-07T06:28:58.540212+00:00 [queued]>
[2025-03-07T06:29:02.809+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-07T06:29:02.819+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): etl_process> on 2025-03-07 06:28:58.540212+00:00
[2025-03-07T06:29:02.836+0000] {standard_task_runner.py:72} INFO - Started process 100 to run task
[2025-03-07T06:29:02.846+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_payments', 'etl_process', 'manual__2025-03-07T06:28:58.540212+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/etl-payments.py', '--cfg-path', '/tmp/tmppjdf6h8u']
[2025-03-07T06:29:02.851+0000] {standard_task_runner.py:105} INFO - Job 151: Subtask etl_process
[2025-03-07T06:29:02.895+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_payments.etl_process manual__2025-03-07T06:28:58.540212+00:00 [running]> on host b1b7220a736d
[2025-03-07T06:29:02.964+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_payments' AIRFLOW_CTX_TASK_ID='etl_process' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T06:28:58.540212+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-07T06:28:58.540212+00:00'
[2025-03-07T06:29:02.968+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-07T06:29:03.002+0000] {etl-payments.py:31} INFO - ðŸ”¹ Mengambil data dari database sumber...
[2025-03-07T06:29:14.438+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/etl-payments.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-03-07T06:29:20.543+0000] {etl-payments.py:36} INFO - âœ… Data berhasil diambil!
[2025-03-07T06:29:20.548+0000] {etl-payments.py:38} INFO - ðŸ”¹ Memproses data...
[2025-03-07T06:29:20.637+0000] {etl-payments.py:59} INFO - âœ… Data berhasil dibersihkan!
[2025-03-07T06:29:46.977+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-07T06:29:46.997+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-07T06:29:46.998+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_payments, task_id=etl_process, run_id=manual__2025-03-07T06:28:58.540212+00:00, execution_date=20250307T062858, start_date=20250307T062902, end_date=20250307T062946
[2025-03-07T06:29:47.034+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-07T06:29:47.043+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-07T06:29:47.043+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
