[2025-03-07T06:43:14.017+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-07T06:43:14.023+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_payments.etl_process manual__2025-03-07T06:43:10.738118+00:00 [queued]>
[2025-03-07T06:43:14.026+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_payments.etl_process manual__2025-03-07T06:43:10.738118+00:00 [queued]>
[2025-03-07T06:43:14.026+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-07T06:43:14.034+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): etl_process> on 2025-03-07 06:43:10.738118+00:00
[2025-03-07T06:43:14.038+0000] {standard_task_runner.py:72} INFO - Started process 86 to run task
[2025-03-07T06:43:14.050+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_payments', 'etl_process', 'manual__2025-03-07T06:43:10.738118+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/etl-payments.py', '--cfg-path', '/tmp/tmpxgguivcs']
[2025-03-07T06:43:14.057+0000] {standard_task_runner.py:105} INFO - Job 158: Subtask etl_process
[2025-03-07T06:43:14.113+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_payments.etl_process manual__2025-03-07T06:43:10.738118+00:00 [running]> on host 98bc23959960
[2025-03-07T06:43:14.213+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_payments' AIRFLOW_CTX_TASK_ID='etl_process' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T06:43:10.738118+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-07T06:43:10.738118+00:00'
[2025-03-07T06:43:14.215+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-07T06:43:14.268+0000] {etl-payments.py:31} INFO - ðŸ”¹ Mengambil data dari database sumber...
[2025-03-07T06:43:20.562+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/etl-payments.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-03-07T06:43:26.979+0000] {etl-payments.py:36} INFO - âœ… Data berhasil diambil!
[2025-03-07T06:43:26.982+0000] {etl-payments.py:38} INFO - ðŸ”¹ Memproses data...
[2025-03-07T06:43:27.114+0000] {etl-payments.py:59} INFO - âœ… Data berhasil dibersihkan!
[2025-03-07T06:43:50.584+0000] {etl-payments.py:99} INFO - âœ… Data baru berhasil dimasukkan ke database!
[2025-03-07T06:43:50.703+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-07T06:43:50.718+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-07T06:43:50.718+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_payments, task_id=etl_process, run_id=manual__2025-03-07T06:43:10.738118+00:00, execution_date=20250307T064310, start_date=20250307T064314, end_date=20250307T064350
[2025-03-07T06:43:50.799+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-07T06:43:50.819+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-07T06:43:50.820+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
